# Generated by Django 4.1 on 2022-08-21 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education", models.JSONField(verbose_name="Education")),
                ("experience", models.JSONField(verbose_name="Experience")),
                ("other_profiles", models.JSONField(verbose_name="Other Profiles")),
                (
                    "date_applied",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Applied"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
