# Generated by Django 4.1 on 2022-08-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_education_experience_delete_application"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="decription",
            new_name="description",
        ),
    ]
