# Generated by Django 4.1 on 2022-08-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_options_remove_user_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_no",
            field=models.IntegerField(default=1234567890, verbose_name="Mobile Number"),
        ),
    ]
