# Generated by Django 4.1 on 2022-08-21 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_mobile_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_mobile",
                        message="Invalid Mobile Number",
                        regex="^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
    ]
